### ISSUE TITLE
"this is bad" comment in requirements.txt

### ISSUE THREAD

**Issue by dequis** [lutostag/dotfiles#2]
requirements.txt says:

```
psycopg2-binary==2.8.5 # this is bad, should not use this
```

No idea what that means and curiosity got the best of me so I had to ask.

Blame says it's from 2019-10-10 and commit log says "dispatcher: mostly working".

**Comment by lutostag** [comment]
Not the most important, but advice from upstream is to not use it for prod https://www.psycopg.org/docs/install.html#psycopg-vs-psycopg-binary

Went over that with Marc a bit, but dunno if he remembers that particularly.

**Comment by dequis** [comment]
Oh okay, yeah, not terribly important in docker-like environments where versions of things are frozen anyway.

Thank you for maintaining this Cool Free open source project!
